In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("big_student_dataset.csv")

In [3]:
overview={}
overview["missing_per_column"] = df.isnull().sum().to_dict()

In [4]:
overview

{'missing_per_column': {'Student_ID': 0,
  'Hours_Studied': 0,
  'Sleep_Hours': 0,
  'Attendance_Percentage': 0,
  'Previous_Score': 0,
  'Social_Media_Hours': 0,
  'Scores': 0,
  'Pass_Fail': 0}}

In [5]:
overview["missing_per_column"].values()

dict_values([0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
overview["missing_per_column"].keys()

dict_keys(['Student_ID', 'Hours_Studied', 'Sleep_Hours', 'Attendance_Percentage', 'Previous_Score', 'Social_Media_Hours', 'Scores', 'Pass_Fail'])

In [7]:
# This is much shorter!
sorted_series = df.isnull().sum().sort_values(ascending=False)

# Then convert to dict if you still need it in that format
overview["missing_per_column"] = sorted_series.to_dict()

In [8]:
overview

{'missing_per_column': {'Student_ID': 0,
  'Hours_Studied': 0,
  'Sleep_Hours': 0,
  'Attendance_Percentage': 0,
  'Previous_Score': 0,
  'Social_Media_Hours': 0,
  'Scores': 0,
  'Pass_Fail': 0}}

In [9]:
# Calculate percentage of missing values


missing_percent = ((df.isnull().sum() / len(df)) * 100).to_dict()

# Sort them to see which columns are missing the most data

In [10]:
type(missing_percent)

dict

In [11]:
type(overview["missing_per_column"])

dict

In [12]:
missing_percent

{'Student_ID': 0.0,
 'Hours_Studied': 0.0,
 'Sleep_Hours': 0.0,
 'Attendance_Percentage': 0.0,
 'Previous_Score': 0.0,
 'Social_Media_Hours': 0.0,
 'Scores': 0.0,
 'Pass_Fail': 0.0}

In [13]:
type(df)

pandas.core.frame.DataFrame

In [14]:
type(df.iloc[0][0])

C:\Users\MSI\AppData\Local\Temp\ipykernel_8668\176430664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  type(df.iloc[0][0])

numpy.int64

In [15]:
exp={
    "numerical" :{
        "count":0,
        "columns":[]
    }
        
}
demo=df.select_dtypes('number')

In [16]:
demo.columns

Index(['Student_ID', 'Hours_Studied', 'Sleep_Hours', 'Attendance_Percentage',
       'Previous_Score', 'Social_Media_Hours', 'Scores'],
      dtype='object')

In [17]:
exp["numerical"]["count"]=demo.shape[1]
exp["numerical"]["columns"]=demo.columns

In [18]:
exp["numerical"]

{'count': 7,
 'columns': Index(['Student_ID', 'Hours_Studied', 'Sleep_Hours', 'Attendance_Percentage',
        'Previous_Score', 'Social_Media_Hours', 'Scores'],
       dtype='object')}

In [19]:
new_df=df.value_counts()

In [20]:
new_df.shape

(120,)

In [21]:
new_df

Student_ID  Hours_Studied  Sleep_Hours  Attendance_Percentage  Previous_Score  Social_Media_Hours  Scores  Pass_Fail
1           3.7            7.2          96                     53              2.3                 62      Pass         1
2           9.5            5.7          66                     30              2.4                 69      Pass         1
3           7.3            5.5          69                     49              2.5                 59      Pass         1
4           5.5            5.4          65                     81              2.8                 51      Pass         1
5           1.6            5.4          52                     80              4.3                 41      Pass         1
                                                                                                                       ..
116         2.6            5.4          85                     37              3.9                 46      Pass         1
117         4.4            7.0          99                     50              4.2                 61      Pass         1
118         7.3            5.6          52                     69              0.4                 60      Pass         1
119         8.9            7.2          89                     32              4.4                 73      Pass         1
120         5.4            4.9          94                     59              2.0                 60      Pass         1
Name: count, Length: 120, dtype: int64

In [22]:
new_df=df.columns.tolist()

In [23]:
type(new_df)

list

In [24]:
df["Attendance_Percentage"].shape[0]

120

In [25]:
type(df["Attendance_Percentage"])

pandas.core.series.Series

In [26]:
columns_name=df.select_dtypes(include=['number']).columns.tolist()

In [27]:
columns_name

['Student_ID',
 'Hours_Studied',
 'Sleep_Hours',
 'Attendance_Percentage',
 'Previous_Score',
 'Social_Media_Hours',
 'Scores']

In [28]:
num=[1,1,1,1,0,0,0]
num.count(1)

4

In [29]:
df.head()

,Student_ID,Hours_Studied,Sleep_Hours,Attendance_Percentage,Previous_Score,Social_Media_Hours,Scores,Pass_Fail
0,1,3.7,7.2,96,53,2.3,62,Pass
1,2,9.5,5.7,66,30,2.4,69,Pass
2,3,7.3,5.5,69,49,2.5,59,Pass
3,4,5.5,5.4,65,81,2.8,51,Pass
4,5,1.6,5.4,52,80,4.3,41,Pass

In [30]:
numeric_data=df.select_dtypes(include=['number']).columns.tolist()
catagorical_data=df.select_dtypes(include=['category']).columns.tolist()

In [31]:
numeric_data

['Student_ID',
 'Hours_Studied',
 'Sleep_Hours',
 'Attendance_Percentage',
 'Previous_Score',
 'Social_Media_Hours',
 'Scores']

In [32]:
my_dict={}
my_dict["numerical_data"]={}
my_dict["categorical_data"]={}

In [33]:
my_dict

{'numerical_data': {}, 'categorical_data': {}}

In [34]:
catagorical_data

[]

In [35]:
for i in numeric_data:
    my_dict["numerical_data"][i]={}

In [36]:
my_dict

{'numerical_data': {'Student_ID': {},
  'Hours_Studied': {},
  'Sleep_Hours': {},
  'Attendance_Percentage': {},
  'Previous_Score': {},
  'Social_Media_Hours': {},
  'Scores': {}},
 'categorical_data': {}}

In [37]:
for i in numeric_data:
    my_dict["numerical_data"][i]["mean"]=df[i].mean().item()
    my_dict["numerical_data"][i]["median"]=df[i].median().item()
    my_dict["numerical_data"][i]["min"]=df[i].min().item()
    my_dict["numerical_data"][i]["max"]=df[i].max().item()

In [38]:
my_dict

{'numerical_data': {'Student_ID': {'mean': 60.5,
   'median': 60.5,
   'min': 1,
   'max': 120},
  'Hours_Studied': {'mean': 4.860833333333333,
   'median': 4.75,
   'min': 0.1,
   'max': 9.8},
  'Sleep_Hours': {'mean': 6.239166666666667,
   'median': 6.15,
   'min': 4.0,
   'max': 8.8},
  'Attendance_Percentage': {'mean': 76.04166666666667,
   'median': 75.0,
   'min': 50,
   'max': 100},
  'Previous_Score': {'mean': 55.65, 'median': 55.0, 'min': 20, 'max': 90},
  'Social_Media_Hours': {'mean': 2.5025,
   'median': 2.45,
   'min': 0.0,
   'max': 4.9},
  'Scores': {'mean': 58.05833333333333, 'median': 59.0, 'min': 29, 'max': 86}},
 'categorical_data': {}}

In [39]:
len(df["Attendance_Percentage"].unique())

49

In [40]:
my_num=df["Pass_Fail"].mode().item()

In [41]:
type(my_num)

str

In [42]:
my_num

'Pass'

In [43]:
df["Pass_Fail"]

0      Pass
1      Pass
2      Pass
3      Pass
4      Pass
       ...
115    Pass
116    Pass
117    Pass
118    Pass
119    Pass
Name: Pass_Fail, Length: 120, dtype: object

In [44]:
df.head()

,Student_ID,Hours_Studied,Sleep_Hours,Attendance_Percentage,Previous_Score,Social_Media_Hours,Scores,Pass_Fail
0,1,3.7,7.2,96,53,2.3,62,Pass
1,2,9.5,5.7,66,30,2.4,69,Pass
2,3,7.3,5.5,69,49,2.5,59,Pass
3,4,5.5,5.4,65,81,2.8,51,Pass
4,5,1.6,5.4,52,80,4.3,41,Pass

In [45]:
data=pd.read_csv("data.csv",encoding="latin1")

In [46]:
(data.isnull().sum().sum()/data.size)*100

np.float64(3.149375633178264)

pandas.core.frame.DataFrame

In [52]:

import json

with open('output.json','r') as file:
    json_data=json.load(file)

In [ ]:
# def insight_agent(final_insights):
#     """
#     Takes analysis output and decides:
#     - summary
#     - warnings
#     - focus areas
#     """
#     agent_output = {
#         "ai_summary": "",
#         "warnings": [],
#         "focus_sections": [],
#         "recommended_actions": []
#     }

#     return agent_output

json_data

{'basic_overview': {'rows': 541909, 'columns': 8},
 'missing_overview': {'total_missing': 136534,
  'missing_percentage': 3.15,
  'missing_count_per_column': {'CustomerID': 135080,
   'Description': 1454,
   'StockCode': 0,
   'InvoiceNo': 0,
   'Quantity': 0,
   'InvoiceDate': 0,
   'UnitPrice': 0,
   'Country': 0},
  'missing_percentage_per_column': {'CustomerID': 24.93,
   'Description': 0.27,
   'StockCode': 0.0,
   'InvoiceNo': 0.0,
   'Quantity': 0.0,
   'InvoiceDate': 0.0,
   'UnitPrice': 0.0,
   'Country': 0.0}},
 'column_types': {'numeric': {'count': 3,
   'columns': ['Quantity', 'UnitPrice', 'CustomerID']},
  'categorical': {'count': 5,
   'columns': ['InvoiceNo',
    'StockCode',
    'Description',
    'InvoiceDate',
    'Country']},
  'datetime': {'count': 0, 'columns': []},
  'boolean': {'count': 0, 'columns': []}},
 'health_checks': {'single_value_columns': [],
  'high_cardinality_columns': [],
  'numeric_as_text_columns': ['InvoiceNo', 'StockCode']},
 'simple_stats': {'numeric_data': {'Quantity': {'mean': 9.55224954743324,
    'median': 3.0,
    'min': -80995,
    'max': 80995},
   'UnitPrice': {'mean': 4.611113626088514,
    'median': 2.08,
    'min': -11062.06,
    'max': 38970.0},
   'CustomerID': {'mean': 15287.690570239585,
    'median': 15152.0,
    'min': 12346.0,
    'max': 18287.0}},
  'categorical_data': {'InvoiceNo': {'unique_values': 25900,
    'most_frequent': '573585'},
   'StockCode': {'unique_values': 4070, 'most_frequent': '85123A'},
   'Description': {'unique_values': 4223,
    'most_frequent': 'WHITE HANGING HEART T-LIGHT HOLDER'},
   'InvoiceDate': {'unique_values': 23260,
    'most_frequent': '10/31/2011 14:41'},
   'Country': {'unique_values': 38, 'most_frequent': 'United Kingdom'}}}}